# Generated by Django 6.0.6 on 2026-07-02 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_front', models.ImageField(upload_to='documents/citizenship/')),
                ('citizenship_back', models.ImageField(upload_to='documents/citizenship/')),
                ('lalpurja', models.ImageField(upload_to='documents/lalpurja/')),
                ('selfie_with_citizenship', models.ImageField(upload_to='documents/selfie/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('single_room', 'Single Room'), ('two_rooms', 'Two Rooms'), ('flat', 'Flat'), ('apartment', 'Apartment'), ('house', 'House'), ('hostel', 'Hostel'), ('office_space', 'Office Space'), ('shutter', 'Shutter')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=200)),
                ('ward_number', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('monthly_rent', models.PositiveIntegerField()),
                ('security_deposit', models.PositiveIntegerField(default=0)),
                ('bills_water', models.BooleanField(default=False)),
                ('bills_electricity', models.BooleanField(default=False)),
                ('bills_internet', models.BooleanField(default=False)),
                ('available_date', models.DateField(blank=True, null=True)),
                ('house_rules', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_owner', models.BooleanField(default=False)),
                ('verified_property', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='core.district')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='core.province')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_parking', models.BooleanField(default=False)),
                ('bike_parking', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('drinking_water', models.BooleanField(default=False)),
                ('water_24_7', models.BooleanField(default=False)),
                ('attached_bathroom', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('cctv', models.BooleanField(default=False)),
                ('security_guard', models.BooleanField(default=False)),
                ('pet_allowed', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
    ]

